services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
      target: ${NODE_ENV:-production}
    env_file:
      - ./apps/client/.env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - 80:80
    # networks:
    #   - app_network

  # server:
  #   container_name: server
  #   build:
  #     context: .
  #     dockerfile: ./apps/server/Dockerfile
  #     args:
  #       - NODE_ENV=${NODE_ENV:-production}
  #     target: ${NODE_ENV:-production}
  #   env_file:
  #     - ./apps/server/.env
  #   environment:
  #     - NODE_ENV=${NODE_ENV:-production}
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - app_network
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:3000/api || exit 1"]
  #     interval: 1m30s
  #     timeout: 30s
  #     retries: 5
  #     start_period: 30s

# networks:
#   app_network:
#     driver: bridge
#     external: true
#     name: bacilica-network
